name: 开始每日签到

on:
  workflow_dispatch:
  schedule:
    # UTC 1点30分(北京时间 9点30分)
    - cron: 30 1 * * *
  # 标星时触发工作流程
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run checkin
        run: |
          python3 glados.py
        env: 
          GLADOS_COOKIE: ${{ secrets.GLADOS_COOKIE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      - name: keep alive
        uses: liskin/gh-workflow-keepalive@v1 # using the workflow with default settings
      - name: delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 10
          delete_run_by_conclusion_pattern: success
 
      # - uses: gautamkrishnar/keepalive-workflow@master  
